// Copyright (C) 2026 quip.network
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
pragma solidity ^0.8.28;

import {Test} from "../lib/forge-std/src/Test.sol";
import {SHRINCS} from "../contracts/SHRINCS.sol";
import {SPHINCSPlusC} from "../contracts/SPHINCSPlusC.sol";
import {SHRINCSParams} from "shrincs-profile/SHRINCSParams.sol";
import {
    SHRINCSAccountVectorExport
} from "./helpers/SHRINCSAccountVectorExport.sol";

// Calldata-shaped entry points for the SHRINCS library calls the exported
// account-wrapper vectors exercise. SHRINCS.verifyStateful/verifyStateless/
// rotateStatefulViaStateless/statelessRotate all take `calldata` public-key
// and signature arguments, so a JSON-decoded (memory) vector can only reach
// them through an external call boundary — mirrors the Stateless128sHarness
// pattern in SHRINCSSphincs128sVectors.t.sol.
contract SHRINCSAccountHarness128s {
    function verifyStatefulExternal(
        bytes32 expectedCommitment,
        SHRINCS.PublicKey calldata publicKey,
        SHRINCS.ActionContext calldata context,
        SHRINCS.Signature calldata signature
    ) external view returns (bool) {
        return SHRINCS.verifyStateful(
            expectedCommitment, publicKey, context, signature
        );
    }

    function verifyStatelessExternal(
        bytes32 expectedCommitment,
        SHRINCS.PublicKey calldata publicKey,
        SHRINCS.ActionContext calldata context,
        SPHINCSPlusC.Signature calldata signature
    ) external view returns (bool) {
        return SHRINCS.verifyStateless(
            expectedCommitment, publicKey, context, signature
        );
    }

    function rotateStatefulViaStatelessExternal(
        bytes32 expectedCommitment,
        SHRINCS.PublicKey calldata currentPublicKey,
        SHRINCS.RotationContext calldata context,
        SPHINCSPlusC.Signature calldata recoverySignature,
        SHRINCS.StatefulRotationTarget calldata nextStatefulKey
    ) external view returns (bytes32) {
        return SHRINCS.rotateStatefulViaStateless(
            expectedCommitment,
            currentPublicKey,
            context,
            recoverySignature,
            nextStatefulKey
        );
    }

    function statelessRotateExternal(
        bytes32 expectedCommitment,
        SHRINCS.PublicKey calldata currentPublicKey,
        SHRINCS.RotationContext calldata context,
        SPHINCSPlusC.Signature calldata recoverySignature,
        SHRINCS.RotationTarget calldata nextKey
    ) external view returns (bytes32) {
        return SHRINCS.statelessRotate(
            expectedCommitment,
            currentPublicKey,
            context,
            recoverySignature,
            nextKey
        );
    }
}

// SHRINCSRustAccountVectors128s: the first Solidity-side consumption of the
// Rust-generated account-wrapper vectors at 128s. testExportStatefulAction
// Bundle/testExportStatelessActionBundle/testExportStatefulOnlyRotation
// Bundle/testExportFullRotationBundle in SHRINCSAccountVectorExport.t.sol
// (skipped at 128s, since that suite signs stateless bundles in-Solidity)
// define the JSON shape this suite consumes: the *_vector_abi blobs
// abi.encode the same SHRINCSAccountVectorExport structs, but produced by
// the Rust signer instead. Runs only under the 128s profiles; the active
// profile's constants and its JSON are selected together.
//
// Fixture provenance: test/test_vectors/shrincs_account_wrapper_vectors_
// 128s_q{18,20}_keccak.json are generated by hashsigs-rs's
// `generate_shrincs_account_wrapper_vectors` (cargo test --release
// --features profile-128s-q18 --test generate_shrincs_vectors
// generate_shrincs_account_wrapper_vectors -- --ignored --nocapture; swap
// profile-128s-q18 for profile-128s-q20 for the q20 twin). This inverts the
// direction of dev/export-account-vectors.sh, which signs in Solidity and
// exports for Rust to consume: at 128s, in-EVM stateless signing (2^24
// FORS-C trees over a fixed 8-layer hypertree) is compute-infeasible, so
// the Rust signer produces the vectors and Solidity only verifies them.
contract SHRINCSRustAccountVectors128sTest is Test {
    SHRINCSAccountHarness128s internal harness;
    string internal vectors;

    function setUp() public {
        // Skip under any non-128s profile: this suite is bound to the 128s
        // vector JSON and constants.
        if (SHRINCSParams.HASH_LEN == 32) return;
        harness = new SHRINCSAccountHarness128s();
        vectors = vm.readFile(vectorPath());
    }

    function vectorPath() internal pure returns (string memory) {
        // q18 and q20 share every field except the stateless-signature
        // budget baked into the FORS-C/hypertree shapes; pick the file by
        // that budget, mirroring SHRINCSSphincs128sVectorsTest.
        if (SHRINCSParams.STATELESS_SIGNATURE_LIMIT == 262_144) {
            // line-length: allow — vector path is one unbreakable token
            return "test/test_vectors/shrincs_account_wrapper_vectors_128s_q18_keccak.json";
        }
        // line-length: allow — vector path is one unbreakable token
        return "test/test_vectors/shrincs_account_wrapper_vectors_128s_q20_keccak.json";
    }

    // ---------------------------------------------------------------
    // Stateful action bundle
    // ---------------------------------------------------------------

    function decodeStatefulActionVector()
        internal
        returns (SHRINCSAccountVectorExport
                    .StatefulActionVector memory vector_)
    {
        bytes memory blob = vm.parseJsonBytes(
            vectors, ".testExportStatefulActionBundle.stateful_vector_abi"
        );
        vector_ = abi.decode(
            blob, (SHRINCSAccountVectorExport.StatefulActionVector)
        );
    }

    function testStatefulActionVerifies() public {
        vm.skip(SHRINCSParams.HASH_LEN == 32);
        SHRINCSAccountVectorExport.StatefulActionVector memory vector_ =
            decodeStatefulActionVector();
        assertTrue(
            harness.verifyStatefulExternal(
                vector_.currentSHRINCSPublicKey,
                vector_.publicKey,
                vector_.context,
                vector_.signature
            ),
            "Rust stateful action vector must verify"
        );
        bytes32 msgHash = SHRINCS.statefulActionMessageHash(
            vector_.currentSHRINCSPublicKey, vector_.context
        );
        assertEq(
            vector_.message,
            abi.encodePacked(msgHash),
            "stateful message must equal statefulActionMessageHash"
        );
    }

    function testMeasureStatefulActionVerifyGas() public {
        vm.skip(SHRINCSParams.HASH_LEN == 32);
        SHRINCSAccountVectorExport.StatefulActionVector memory vector_ =
            decodeStatefulActionVector();
        uint256 before = gasleft();
        bool ok = harness.verifyStatefulExternal(
            vector_.currentSHRINCSPublicKey,
            vector_.publicKey,
            vector_.context,
            vector_.signature
        );
        uint256 used = before - gasleft();
        assertTrue(ok, "stateful vector must verify for gas measurement");
        emit log_named_uint("account.stateful_verify_gas", used);
    }

    function testStatefulActionTamperedRandomizerFails() public {
        vm.skip(SHRINCSParams.HASH_LEN == 32);
        SHRINCSAccountVectorExport.StatefulActionVector memory vector_ =
            decodeStatefulActionVector();
        vector_.signature.randomizer =
            vector_.signature.randomizer ^ bytes32(uint256(1));
        assertTrue(
            statefulVerifyRejected(vector_),
            "tampered stateful randomizer must not wrong-accept"
        );
    }

    function statefulVerifyRejected(
        SHRINCSAccountVectorExport.StatefulActionVector memory vector_
    ) internal returns (bool) {
        try harness.verifyStatefulExternal(
            vector_.currentSHRINCSPublicKey,
            vector_.publicKey,
            vector_.context,
            vector_.signature
        ) returns (
            bool ok
        ) {
            return !ok;
        } catch {
            return true;
        }
    }

    // ---------------------------------------------------------------
    // Stateless action bundle
    // ---------------------------------------------------------------

    function decodeStatelessActionVector()
        internal
        returns (SHRINCSAccountVectorExport
                    .StatelessActionVector memory vector_)
    {
        bytes memory blob =
            vm.parseJsonBytes(
                vectors,
                ".testExportStatelessActionBundle.stateless_vector_abi"
            );
        vector_ = abi.decode(
            blob, (SHRINCSAccountVectorExport.StatelessActionVector)
        );
    }

    function testStatelessActionVerifies() public {
        vm.skip(SHRINCSParams.HASH_LEN == 32);
        SHRINCSAccountVectorExport.StatelessActionVector memory vector_ =
            decodeStatelessActionVector();
        assertTrue(
            harness.verifyStatelessExternal(
                vector_.currentSHRINCSPublicKey,
                vector_.publicKey,
                vector_.context,
                vector_.signature
            ),
            "Rust stateless action vector must verify"
        );
        bytes32 msgHash = SHRINCS.statelessActionMessageHash(
            vector_.currentSHRINCSPublicKey, vector_.context
        );
        assertEq(
            vector_.message,
            abi.encodePacked(msgHash),
            "stateless message must equal statelessActionMessageHash"
        );
    }

    function testMeasureStatelessActionVerifyGas() public {
        vm.skip(SHRINCSParams.HASH_LEN == 32);
        SHRINCSAccountVectorExport.StatelessActionVector memory vector_ =
            decodeStatelessActionVector();
        uint256 before = gasleft();
        bool ok = harness.verifyStatelessExternal(
            vector_.currentSHRINCSPublicKey,
            vector_.publicKey,
            vector_.context,
            vector_.signature
        );
        uint256 used = before - gasleft();
        assertTrue(ok, "stateless vector must verify for gas measurement");
        emit log_named_uint("account.stateless_verify_gas", used);
    }

    function testStatelessActionTamperedRandomizerFails() public {
        vm.skip(SHRINCSParams.HASH_LEN == 32);
        SHRINCSAccountVectorExport.StatelessActionVector memory vector_ =
            decodeStatelessActionVector();
        vector_.signature.fors.randomizer[0] =
            vector_.signature.fors.randomizer[0] ^ bytes1(uint8(1));
        assertTrue(
            statelessVerifyRejected(vector_),
            "tampered stateless randomizer must not wrong-accept"
        );
    }

    function statelessVerifyRejected(
        SHRINCSAccountVectorExport.StatelessActionVector memory vector_
    ) internal returns (bool) {
        try harness.verifyStatelessExternal(
            vector_.currentSHRINCSPublicKey,
            vector_.publicKey,
            vector_.context,
            vector_.signature
        ) returns (
            bool ok
        ) {
            return !ok;
        } catch {
            return true;
        }
    }

    // ---------------------------------------------------------------
    // Stateful-only rotation bundle
    // ---------------------------------------------------------------

    function decodeStatefulOnlyRotationVector()
        internal
        returns (SHRINCSAccountVectorExport
                    .StatefulOnlyRotationVector memory vector_)
    {
        bytes memory blob =
            vm.parseJsonBytes(
                vectors,
                // line-length: allow — JSON path is one unbreakable token
                ".testExportStatefulOnlyRotationBundle.stateful_rotation_vector_abi"
            );
        vector_ = abi.decode(
            blob, (SHRINCSAccountVectorExport.StatefulOnlyRotationVector)
        );
    }

    function testStatefulOnlyRotationReturnsNextCommitment() public {
        vm.skip(SHRINCSParams.HASH_LEN == 32);
        SHRINCSAccountVectorExport.StatefulOnlyRotationVector memory
            vector_ = decodeStatefulOnlyRotationVector();
        bytes32 expectedNext = toBytes32(vector_.nextKey.publicKeyCommitment);
        bytes32 nextCommitment = harness.rotateStatefulViaStatelessExternal(
            vector_.currentSHRINCSPublicKey,
            vector_.currentPublicKey,
            vector_.context,
            vector_.recoverySignature,
            vector_.nextKey
        );
        assertTrue(
            nextCommitment != bytes32(0),
            "Rust stateful-only rotation vector must not fail"
        );
        assertEq(
            nextCommitment,
            expectedNext,
            "rotation must return the vector's declared next commitment"
        );
    }

    function testMeasureStatefulOnlyRotationGas() public {
        vm.skip(SHRINCSParams.HASH_LEN == 32);
        SHRINCSAccountVectorExport.StatefulOnlyRotationVector memory
            vector_ = decodeStatefulOnlyRotationVector();
        uint256 before = gasleft();
        bytes32 nextCommitment = harness.rotateStatefulViaStatelessExternal(
            vector_.currentSHRINCSPublicKey,
            vector_.currentPublicKey,
            vector_.context,
            vector_.recoverySignature,
            vector_.nextKey
        );
        uint256 used = before - gasleft();
        assertTrue(
            nextCommitment != bytes32(0),
            "rotation must succeed for gas measurement"
        );
        emit log_named_uint("account.stateful_only_rotation_gas", used);
    }

    function testStatefulOnlyRotationTamperedRandomizerReturnsZero() public {
        vm.skip(SHRINCSParams.HASH_LEN == 32);
        SHRINCSAccountVectorExport.StatefulOnlyRotationVector memory
            vector_ = decodeStatefulOnlyRotationVector();
        vector_.recoverySignature.fors.randomizer[0] =
            vector_.recoverySignature.fors.randomizer[0] ^ bytes1(uint8(1));
        assertTrue(
            statefulOnlyRotationRejected(vector_),
            "tampered stateful-only rotation randomizer must not wrong-accept"
        );
    }

    function statefulOnlyRotationRejected(
        SHRINCSAccountVectorExport.StatefulOnlyRotationVector memory vector_
    ) internal returns (bool) {
        try harness.rotateStatefulViaStatelessExternal(
            vector_.currentSHRINCSPublicKey,
            vector_.currentPublicKey,
            vector_.context,
            vector_.recoverySignature,
            vector_.nextKey
        ) returns (
            bytes32 nextCommitment
        ) {
            return nextCommitment == bytes32(0);
        } catch {
            return true;
        }
    }

    // ---------------------------------------------------------------
    // Full rotation bundle
    // ---------------------------------------------------------------

    function decodeFullRotationVector()
        internal
        returns (SHRINCSAccountVectorExport
                    .FullRotationVector memory vector_)
    {
        bytes memory blob = vm.parseJsonBytes(
            vectors, ".testExportFullRotationBundle.full_rotation_vector_abi"
        );
        vector_ = abi.decode(
            blob, (SHRINCSAccountVectorExport.FullRotationVector)
        );
    }

    function testFullRotationReturnsNextCommitment() public {
        vm.skip(SHRINCSParams.HASH_LEN == 32);
        SHRINCSAccountVectorExport.FullRotationVector memory vector_ =
            decodeFullRotationVector();
        bytes32 expectedNext = toBytes32(vector_.nextKey.publicKeyCommitment);
        bytes32 nextCommitment = harness.statelessRotateExternal(
            vector_.currentSHRINCSPublicKey,
            vector_.currentPublicKey,
            vector_.context,
            vector_.recoverySignature,
            vector_.nextKey
        );
        assertTrue(
            nextCommitment != bytes32(0),
            "Rust full rotation vector must not fail"
        );
        assertEq(
            nextCommitment,
            expectedNext,
            "rotation must return the vector's declared next commitment"
        );
    }

    function testMeasureFullRotationGas() public {
        vm.skip(SHRINCSParams.HASH_LEN == 32);
        SHRINCSAccountVectorExport.FullRotationVector memory vector_ =
            decodeFullRotationVector();
        uint256 before = gasleft();
        bytes32 nextCommitment = harness.statelessRotateExternal(
            vector_.currentSHRINCSPublicKey,
            vector_.currentPublicKey,
            vector_.context,
            vector_.recoverySignature,
            vector_.nextKey
        );
        uint256 used = before - gasleft();
        assertTrue(
            nextCommitment != bytes32(0),
            "rotation must succeed for gas measurement"
        );
        emit log_named_uint("account.full_rotation_gas", used);
    }

    function testFullRotationTamperedRandomizerReturnsZero() public {
        vm.skip(SHRINCSParams.HASH_LEN == 32);
        SHRINCSAccountVectorExport.FullRotationVector memory vector_ =
            decodeFullRotationVector();
        vector_.recoverySignature.fors.randomizer[0] =
            vector_.recoverySignature.fors.randomizer[0] ^ bytes1(uint8(1));
        assertTrue(
            fullRotationRejected(vector_),
            "tampered full rotation randomizer must not wrong-accept"
        );
    }

    function fullRotationRejected(
        SHRINCSAccountVectorExport.FullRotationVector memory vector_
    ) internal returns (bool) {
        try harness.statelessRotateExternal(
            vector_.currentSHRINCSPublicKey,
            vector_.currentPublicKey,
            vector_.context,
            vector_.recoverySignature,
            vector_.nextKey
        ) returns (
            bytes32 nextCommitment
        ) {
            return nextCommitment == bytes32(0);
        } catch {
            return true;
        }
    }

    // ---------------------------------------------------------------
    // Shared helpers
    // ---------------------------------------------------------------

    function toBytes32(bytes memory data)
        internal
        pure
        returns (bytes32 word)
    {
        require(data.length == 32, "expected a 32-byte word");
        // Memory-safe: reads one word starting past the length prefix; no
        // memory is written.
        assembly ("memory-safe") {
            word := mload(add(data, 32))
        }
    }
}
