[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
gas_limit = "18446744073709551615" # u64::MAX

[profile.production]
via_ir = true
optimizer = true
optimizer_runs = 1000000
contract_size_limit = 24576 # Optional: limits contract size to 24KB
gas_limit = "18446744073709551615" # u64::MAX
no_console = true

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = 'long'
multiline_func_header = 'attributes_first'
quote_style = 'double'
number_underscore = 'preserve'
single_line_statement_blocks = 'preserve'